spring:
  application:
    name: digital_detox

  datasource:
    url: jdbc:mysql://localhost:3306/digital_detox?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /
